vich_uploader:
  db_driver: orm

  mappings:
    user_profile:
      uri_prefix: /images/users
      upload_destination: '%kernel.project_dir%/public/images/users'
      namer: Vich\UploaderBundle\Naming\UniqidNamer

    client_profile:
      uri_prefix: /images/clients
      upload_destination: '%kernel.project_dir%/public/images/clients'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    permis_chauffeur:
      uri_prefix: /images/permis
      upload_destination: '%kernel.project_dir%/public/images/permis'
      namer: Vich\UploaderBundle\Naming\UniqidNamer

    bon_chauffeur:
      uri_prefix: /images/bons
      upload_destination: '%kernel.project_dir%/public/images/bons'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
